# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('sites', '0004_auto_20160810_2005'),
        ('djangocms_news', '0002_auto_20170119_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotednews',
            name='extract',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text='A brief description of the article used in the featured lists', verbose_name='extract'),
        ),
        migrations.AddField(
            model_name='promotednews',
            name='site',
            field=models.ForeignKey(default=1, help_text='The site the article is accessible from', on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_articles', to='sites.Site', verbose_name='site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotednews',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image'),
        ),
    ]
