# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 14:35
from __future__ import unicode_literals

import django.contrib.sites.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20160515_1433'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='site',
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
