# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_googlecalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendar',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
